# Generated by Django 6.0 on 2025-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='school_v2_a_date_030c24_idx'),
        ),
    ]
